# Generated by Django 3.2.6 on 2021-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_avatar_profile_avatar1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar1',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars/'),
        ),
    ]
